# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example --repo-update
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/EasyTuple.xcworkspace -scheme iOSTests -sdk iphonesimulator11.0 -destination 'platform=iOS Simulator,name=iPhone 6s Plus,OS=11.0' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
